version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "yarn"
      include: "scope" # Añade (deps) o (deps-dev) según el tipo de dependencia
    open-pull-requests-limit: 4
    versioning-strategy: "increase" # Actualiza en el package.json y yarn.lock
